import pathlib
from typing import Any
import urllib.parse

import fsspec


class UPath(pathlib.PurePosixPath):
    def __init__(self, url: str, **extra: Any) -> None: ...
    fs: fsspec.spec.AbstractFileSystem
    path: str
    _url: urllib.parse.ParseResult

    def __div__(self, other: str) -> UPath: ...

    def read_text(self) -> str: ...

    def write_text(self, text: str) -> None: ...

    def read_bytes(self) -> bytes: ...

    def write_bytes(self, text: bytes) -> None: ...

    def unlink(self) -> None: ...

    def exists(self) -> bool: ...

    def mkdir(self, exist_ok: bool = ..., parents: bool = ...) -> bool: ...

    def glob(self, pattern: str) -> Iterable[UPath]: ...
